### ISSUE TITLE
error on python3.7

### ISSUE THREAD

**Issue by knok** [wtsnjp/twoot.py#1]
I used this with python 3.7, it causes error:

```
python3 twoot.py --log ./log
Traceback (most recent call last):
  File "twoot.py", line 968, in <module>
    main()
  File "twoot.py", line 960, in main
    twoot = Twoot(profile, setup)
  File "twoot.py", line 167, in __init__
    self.config = json.loads(f.read(), 'utf-8')
TypeError: loads() takes 1 positional argument but 2 were given
```

I can work with the following modifying:

```
diff --git a/twoot.py b/twoot.py
index bcb524a..e7ae0d4 100644
--- a/twoot.py
+++ b/twoot.py
@@ -164,7 +164,7 @@ class Twoot:
             # load config
             logger.debug('Loading config file {}'.format(self.config_file))
             with open(self.config_file) as f:
-                self.config = json.loads(f.read(), 'utf-8')
+                self.config = json.loads(f.read() , encoding='utf-8')
 
             # setup Mastodon
             ms = self.config['mastodon']
```

**Comment by wtsnjp** [comment]
Thank you for reporting that!
